import { useEffect, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { create_suggested_pull_request, get_pull_requests } from '../services/api'
import type { PullRequest } from '../types/PullRequest'

function formatDate(value: string): string {
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return value
  return d.toISOString().replace('T', ' ').replace('Z', ' UTC')
}

export default function PullRequests() {
  const [pullRequests, setPullRequests] = useState<PullRequest[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [creatingId, setCreatingId] = useState<number | null>(null)
  const [statusMessage, setStatusMessage] = useState<string | null>(null)
  const [confirmTarget, setConfirmTarget] = useState<PullRequest | null>(null)

  useEffect(() => {
    let cancelled = false

    async function loadPullRequests() {
      try {
        const result = await get_pull_requests()
        if (!cancelled) {
          setPullRequests(result)
          setError(null)
          setLoading(false)
        }
      } catch (e) {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : 'Failed to load pull requests')
          setLoading(false)
        }
      }
    }

    loadPullRequests()
    return () => {
      cancelled = true
    }
  }, [])

  return (
    <>
      <section className="rounded-2xl border border-zinc-800/80 bg-zinc-900/60 p-8 shadow-[0_10px_40px_rgba(0,0,0,0.35)]">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-sky-400/80">Suggested Changes</p>
        <h1 className="page-title mt-3 text-4xl font-extrabold tracking-tight text-zinc-50">Suggested Pull Requests</h1>
        <div className="mt-4 h-px w-28 bg-linear-to-r from-sky-400/80 to-transparent" />
        <p className="mt-4 text-sm text-zinc-300">
          These are suggested pull requests generated by the agent. Review one and click <span className="font-semibold text-zinc-100">Create PR</span> to publish it to GitHub.
        </p>

        {loading ? (
          <ul className="mt-5 space-y-3">
            {[0, 1, 2].map((idx) => (
              <li key={idx} className="rounded-lg border border-zinc-800 bg-zinc-950/70 p-4">
                <div className="h-4 w-64 animate-pulse rounded bg-zinc-800" />
                <div className="mt-3 h-3 w-40 animate-pulse rounded bg-zinc-800/80" />
              </li>
            ))}
          </ul>
        ) : null}

        {error ? <p className="mt-5 text-sm text-rose-300">{error}</p> : null}
        {statusMessage ? <p className="mt-5 text-sm text-emerald-300">{statusMessage}</p> : null}

        {!loading ? (
          <ul className="mt-5 space-y-3">
            {pullRequests.length === 0 ? (
              <li className="rounded-lg border border-zinc-800 bg-zinc-950/70 px-4 py-3 text-zinc-400">
                No pull requests found.
              </li>
            ) : (
              [...pullRequests]
                .sort((a, b) => b.id - a.id)
                .map((pr) => (
                  <li key={pr.id} className="rounded-lg border border-zinc-800 bg-zinc-950/70">
                    <details className="group">
                      <summary className="flex cursor-pointer list-none items-center justify-between gap-4 px-4 py-3">
                        <div className="flex min-w-0 items-center gap-3">
                          <span className="mt-0.5 inline-flex h-5 w-5 items-center justify-center rounded text-xs text-zinc-400 transition-transform group-open:rotate-90">
                            <i className="fa-solid fa-chevron-right"></i>
                          </span>
                          <div className="min-w-0">
                            <h2 className="truncate text-lg font-semibold text-zinc-100">{pr.title}</h2>
                            <p className="mt-1 text-xs text-zinc-400">{pr.repo_owner}/{pr.repo_name}</p>
                          </div>
                        </div>
                        <span className="rounded border border-sky-500/30 bg-sky-500/20 px-2 py-0.5 text-xs text-sky-200">
                          Suggestion #{pr.id}
                        </span>
                      </summary>

                      <div className="border-t border-zinc-800 px-4 py-3">
                        <div className="mb-3 text-xs text-zinc-400">
                          <span className="rounded-md border border-zinc-800 bg-zinc-900/60 p-1">{pr.head_branch}</span>
                          <i className="fa-solid fa-arrow-right-long mx-2 text-blue-400"></i>
                          <span className="rounded-md border border-zinc-800 bg-zinc-900/60 p-1">{pr.base_branch}</span>
                        </div>
                        <div className="rounded-md border border-zinc-800 bg-zinc-900/60 p-3">
                          <div className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-zinc-400">Description</div>
                          <div className="text-sm text-zinc-300">
                            <ReactMarkdown
                              remarkPlugins={[remarkGfm]}
                              components={{
                                p: ({ children }) => <p className="mb-2 last:mb-0">{children}</p>,
                                ul: ({ children }) => <ul className="mb-2 list-disc space-y-1 pl-5 last:mb-0">{children}</ul>,
                                ol: ({ children }) => <ol className="mb-2 list-decimal space-y-1 pl-5 last:mb-0">{children}</ol>,
                                li: ({ children }) => <li>{children}</li>,
                                code: ({ children }) => <code className="rounded bg-zinc-800 px-1.5 py-0.5 text-xs text-zinc-200">{children}</code>,
                                pre: ({ children }) => <pre className="mb-2 overflow-x-auto rounded bg-zinc-950 p-2 text-xs text-zinc-200">{children}</pre>,
                                a: ({ children, href }) => (
                                  <a href={href} target="_blank" rel="noreferrer" className="text-sky-300 hover:text-sky-200 hover:underline">
                                    {children}
                                  </a>
                                ),
                              }}
                            >
                              {pr.body}
                            </ReactMarkdown>
                          </div>
                        </div>

                        <div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-zinc-400">
                          <a
                            href={pr.compare_url}
                            target="_blank"
                            rel="noreferrer"
                            className="text-sky-300 hover:text-sky-200 hover:underline"
                          >
                            Open Compare
                          </a>
                          <span>Created: {formatDate(pr.created_at)}</span>
                          <button
                            type="button"
                            disabled={creatingId === pr.id}
                            onClick={() => setConfirmTarget(pr)}
                            className="flex flex-row items-center gap-2 rounded border border-sky-500/40 bg-sky-500/20 px-3 py-2 text-sm ml-auto cursor-pointer font-medium text-sky-200 hover:bg-sky-500/30 disabled:cursor-not-allowed disabled:opacity-50"
                          >
                            <i className="fa-solid fa-code-pull-request"></i>
                            {creatingId === pr.id ? 'Creating...' : 'Create PR'}
                          </button>
                        </div>
                      </div>
                    </details>
                  </li>
                ))
            )}
          </ul>
        ) : null}
      </section>

      {confirmTarget ? (
        <div onClick={() => setConfirmTarget(null)} className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 px-4">
          <div onClick={(e) => {e.stopPropagation()}} className="w-full max-w-md rounded-xl border border-zinc-800 bg-zinc-900 p-5 shadow-[0_20px_60px_rgba(0,0,0,0.55)]">
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-sky-400/80">Confirm Action</p>
            <h2 className="mt-2 text-xl font-semibold text-zinc-100">Create GitHub Pull Request?</h2>
            <p className="mt-3 text-sm text-zinc-300">
              This will create a GitHub pull request from suggestion <span className="font-semibold text-zinc-100">#{confirmTarget.id}</span>.
            </p>
            <p className="mt-2 truncate text-sm text-zinc-400">{confirmTarget.title}</p>

            <div className="mt-5 flex items-center justify-end gap-2">
              <button
                type="button"
                onClick={() => setConfirmTarget(null)}
                className="rounded cursor-pointer border border-zinc-700 bg-zinc-800 px-3 py-1.5 text-sm text-zinc-200 hover:bg-zinc-700"
              >
                Cancel
              </button>
              <button
                type="button"
                disabled={creatingId === confirmTarget.id}
                onClick={async () => {
                  setStatusMessage(null)
                  setError(null)
                  setCreatingId(confirmTarget.id)
                  try {
                    await create_suggested_pull_request(confirmTarget.id)
                    setPullRequests((prev) => prev.filter((item) => item.id !== confirmTarget.id))
                    setStatusMessage(`Created GitHub pull request from suggestion #${confirmTarget.id}.`)
                    setConfirmTarget(null)
                  } catch (e) {
                    setError(e instanceof Error ? e.message : 'Failed to create pull request')
                  } finally {
                    setCreatingId(null)
                  }
                }}
                className="rounded cursor-pointer border border-sky-500/40 bg-sky-500/20 px-3 py-1.5 text-sm font-medium text-sky-200 hover:bg-sky-500/30 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {creatingId === confirmTarget.id ? 'Creating...' : 'Create PR'}
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </>
  )
}
